"""Build the corpus map from the fact matrix: which facts change in which edition.

    uv run python scripts/build_corpus_map.py > documentation/design/corpus_map.md

The fact matrix is convenience data. This script also reports where the matrix asserts a
value for a clause that doesn't exist in that edition: the table-vs-wording trap (DTI-014),
handled as a class rather than one instance.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

MATRIX = Path(__file__).resolve().parents[1] / "data" / "fact_matrix" / "editions_fact_matrix.csv"

EDITION_COLUMNS = [
    "doc_id",
    "edition_year",
    "version",
    "status",
    "published",
    "effective_from",
    "effective_to",
    "supersedes",
    "superseded_by",
]
MONEY_FACTS = {
    "standard_excess",
    "eow_wetroom_excess",
    "trace_access_limit",
    "outbuildings_limit",
    "flood_excess",
    "emergency_repair_limit",
    "pedal_cycle_limit",
    "ad_excess",
    "buildings_limit",
    "contents_limit",
    "fuel_limit",
    "he_limit",
}
# A numeric limit only means something if the clause it limits exists in that edition.
LIMIT_REQUIRES_CLAUSE = {"he_limit": "home_emergency", "fuel_limit": "escape_of_fuel"}


def load(path: Path = MATRIX) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def is_bool(values: list[str]) -> bool:
    return all(v in ("True", "False") for v in values)


def display(key: str, value: str) -> str:
    if key in MONEY_FACTS and value.isdigit():
        return f"£{int(value):,}"
    return value


def label(row: dict[str, str]) -> str:
    return f"{row['edition_year']} v{row['version']}"


def editions_table(rows: list[dict[str, str]]) -> list[str]:
    out = [
        "| doc_id | Year | Ver | Status | Effective from | Effective to |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| `{r['doc_id']}` | {r['edition_year']} | {r['version']} | {r['status']} "
            f"| {r['effective_from']} | {r['effective_to']} |"
        )
    return out


def changes_table(rows: list[dict[str, str]], facts: list[str]) -> list[str]:
    out = ["| Fact | " + " | ".join(label(r) for r in rows) + " |", "|---" * (len(rows) + 1) + "|"]
    for fact in facts:
        cells, previous = [], None
        for r in rows:
            clause = LIMIT_REQUIRES_CLAUSE.get(fact)
            if clause and r[clause] == "False":
                cell = "—"
            else:
                cell = display(fact, r[fact])
                if previous is not None and cell != previous:
                    cell = f"**{cell}**"
            previous = cell.strip("*") if cell != "—" else previous
            cells.append(cell)
        out.append(f"| `{fact}` | " + " | ".join(cells) + " |")
    return out


def clause_table(rows: list[dict[str, str]], clauses: list[str]) -> list[str]:
    out = ["| Clause | First appears |", "|---|---|"]
    for clause in clauses:
        first = next((label(r) for r in rows if r[clause] == "True"), "never")
        out.append(f"| `{clause}` | {first} |")
    return out


def table_vs_wording(rows: list[dict[str, str]]) -> list[str]:
    out = []
    for limit, clause in LIMIT_REQUIRES_CLAUSE.items():
        for r in rows:
            if r[clause] == "False" and r[limit] not in ("", "None"):
                out.append(
                    f"- `{r['doc_id']}`: `{limit}` = {display(limit, r[limit])} but "
                    f"`{clause}` = False. The wording has no such clause; ignore the value."
                )
    return out


def main() -> None:
    rows = load()
    fact_columns = [c for c in rows[0] if c not in EDITION_COLUMNS]
    bools = [c for c in fact_columns if is_bool([r[c] for r in rows])]
    numbers = [c for c in fact_columns if c not in bools]
    changing = [c for c in numbers if len({r[c] for r in rows}) > 1]

    lines = [
        "# Corpus map",
        "",
        "Generated by `scripts/build_corpus_map.py` from "
        "`data/fact_matrix/editions_fact_matrix.csv`.",
        "The matrix is convenience data: every value here must be confirmed against the wording.",
        "",
        "## Editions",
        "",
        *editions_table(rows),
        "",
        "## What changes where (bold = changed from the previous edition)",
        "",
        *changes_table(rows, changing),
        "",
        "## Clause existence",
        "",
        *clause_table(rows, bools),
        "",
        "## Table-vs-wording conflicts",
        "",
        *(table_vs_wording(rows) or ["None found."]),
        "",
    ]
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
