# The app's configuration for this environment. Terraform knows every value, so it writes
# deploy/<env>.env itself: the file the Python code reads locally, and the pipeline pushes to
# the running app. Commit it after an apply that changes it.

locals {
  settings = {
    APP_ENV                       = local.env
    AZURE_OPENAI_ENDPOINT         = "https://${azurerm_cognitive_account.foundry.custom_subdomain_name}.openai.azure.com/"
    AZURE_OPENAI_API_VERSION      = local.shared.openai_api_version
    AZURE_OPENAI_CHAT_DEPLOYMENT  = azurerm_cognitive_deployment.chat.name
    AZURE_OPENAI_EMBED_DEPLOYMENT = azurerm_cognitive_deployment.embed.name
    AZURE_SEARCH_ENDPOINT         = "https://${azurerm_search_service.this.name}.search.windows.net"
    AZURE_SEARCH_API_VERSION      = local.shared.search_api_version
    AZURE_SUBSCRIPTION_ID         = local.cfg.subscription_id
    AZURE_RESOURCE_GROUP          = azurerm_resource_group.this.name
    AZURE_FOUNDRY_ACCOUNT         = azurerm_cognitive_account.foundry.name
    AZURE_STORAGE_ACCOUNT         = azurerm_storage_account.this.name
    AZURE_OPENAI_JUDGE_DEPLOYMENT = one(azurerm_cognitive_deployment.judge[*].name) == null ? "" : "judge"
    AZURE_AI_SERVICES_ENDPOINT    = azurerm_cognitive_account.foundry.endpoint
    APP_IDENTITY_CLIENT_ID        = azurerm_user_assigned_identity.app.client_id
    TRACE_SAMPLING_RATIO          = tostring(local.e.trace_sampling_ratio)
    # An ingestion key, not a credential: it can send telemetry, not read it. The provider
    # marks it sensitive; this project commits it, knowingly.
    APPLICATIONINSIGHTS_CONNECTION_STRING = nonsensitive(azurerm_application_insights.this.connection_string)
  }
}

resource "local_file" "env" {
  filename        = var.env_file
  file_permission = "0644"
  content         = <<-EOT
    # ${local.env}: non-secret configuration, GENERATED by `terraform apply` in infra/${local.env}.
    # Don't edit it. Change deploy/environments.yaml (or infra/), apply, and commit this file.
    # No keys: auth is Entra ID (DefaultAzureCredential) everywhere.

    APP_ENV=${local.settings.APP_ENV}

    # Foundry / Azure OpenAI (Lesson 01)
    AZURE_OPENAI_ENDPOINT=${local.settings.AZURE_OPENAI_ENDPOINT}
    AZURE_OPENAI_API_VERSION=${local.settings.AZURE_OPENAI_API_VERSION}
    AZURE_OPENAI_CHAT_DEPLOYMENT=${local.settings.AZURE_OPENAI_CHAT_DEPLOYMENT}
    AZURE_OPENAI_EMBED_DEPLOYMENT=${local.settings.AZURE_OPENAI_EMBED_DEPLOYMENT}

    # Azure AI Search (Lesson 01). The index name is NOT here: it is versioned in code (Lesson 04).
    AZURE_SEARCH_ENDPOINT=${local.settings.AZURE_SEARCH_ENDPOINT}
    AZURE_SEARCH_API_VERSION=${local.settings.AZURE_SEARCH_API_VERSION}

    # Management-plane coordinates: which model versions are serving (Lesson 04) and drift
    # checks (Lesson 13).
    AZURE_SUBSCRIPTION_ID=${local.settings.AZURE_SUBSCRIPTION_ID}
    AZURE_RESOURCE_GROUP=${local.settings.AZURE_RESOURCE_GROUP}
    AZURE_FOUNDRY_ACCOUNT=${local.settings.AZURE_FOUNDRY_ACCOUNT}

    # Storage (Lesson 04 experiment; Lesson 13 audit log)
    AZURE_STORAGE_ACCOUNT=${local.settings.AZURE_STORAGE_ACCOUNT}

    # Judge model for evaluation (Lesson 10). dev and test only; blank in prod, always.
    AZURE_OPENAI_JUDGE_DEPLOYMENT=${local.settings.AZURE_OPENAI_JUDGE_DEPLOYMENT}

    # Groundedness detection (Lesson 11): the same Foundry resource, cognitiveservices host.
    AZURE_AI_SERVICES_ENDPOINT=${local.settings.AZURE_AI_SERVICES_ENDPOINT}

    # The app's user-assigned managed identity (Lesson 12)
    APP_IDENTITY_CLIENT_ID=${local.settings.APP_IDENTITY_CLIENT_ID}

    # Observability (Lesson 13)
    APPLICATIONINSIGHTS_CONNECTION_STRING=${local.settings.APPLICATIONINSIGHTS_CONNECTION_STRING}
    TRACE_SAMPLING_RATIO=${local.settings.TRACE_SAMPLING_RATIO}
  EOT
}
